##ansible task for installing docker 

---
- name: purge lxc_docker
  apt: name='lxc-docker*' purge=yes state=absent
  ignore_errors: true

- name: purge lxc-io
  apt: name='lxc-io*' purge=yes state=absent
  ignore_errors: true

- name: add docker key
  apt_key: keyserver={{ docker_key }} id={{ docker_id }}

- name: create docker repo list
  copy: content={{ docker_repo_jessie }} dest=/etc/apt/sources.list.d/docker.list
  when: ansible_distribution == "Debian" and ansible_distribution_release == "jessie"

- name: create docker repo list
  copy: content={{ docker_repo_wheezy }} dest=/etc/apt/sources.list.d/docker.list
  when: ansible_distribution == "Debian" and ansible_distribution_release == "wheezy"

- name: create docker repo list
  copy: content={{ docker_repo_stretch }} dest=/etc/apt/sources.list.d/docker.list
  when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"

- name: install docker
  apt: name=docker-engine state=latest update_cache=yes

- name: install docker utilities
  copy: src={{ item }} dest=/usr/local/bin owner=root mode=755
  with_fileglob:
    - utils/*

- name: set docker options
  lineinfile: dest=/etc/default/docker regexp=^DOCKER_OPTS= line='{{ docker_opts }}'

- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.5.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }} dest=/usr/local/bin/docker-compose mode=755

